### ISSUE TITLE
Binary Writer

### ISSUE THREAD

**Issue by faineance** [haskell-wasm/wasm#2]
http://webassembly.org/docs/binary-encoding/
## Serialize instances
- [ ] binary operations 
- [x] comparison operators 
- [ ] float values
- [ ] imports/exports
- [ ] control flow
- [ ] variable access
- [x] memory related operators
- [ ] function params
- [ ] modules
## Testing
Generate binary outputs for [test suite](https://github.com/haskell-wasm/wasm/tree/master/test) and compare to output from [reference implementation](https://github.com/WebAssembly/wabt#running-wast2wasm).

**Comment by sdiehl** [comment]
@faineance These are also quite useful resources for the binary protocol:

- http://webassembly.org/docs/binary-encoding/
- https://mbebenita.github.io/WasmExplorer/

**Comment by faineance** [comment]
Thanks! The WasmExplorer looks particularly cool
