### ISSUE TITLE
Project status and goals

### ISSUE THREAD

**Issue by SPY** [haskell-wasm/wasm#22]
Hi.
I was interesting in tool for WebAssembly code generation for Haskell and found this repo.
My aim is to write Cmm to WebAssembly translator.
After codebase inspection I realized its wasm text format parsing capabilities very far from spec description.
At first, I was going to improve existing parser, but after first attempt I found out it is easer to write it from scratch. I did it in my own repo - https://github.com/SPY/haskell-wasm
So, my question is what status and goals of this project? Do our intentions meet in some way? Can we join our efforts?

**Comment by sdiehl** [comment]
Sure, I'll add you to the project. There are a lot of things that need to be brought to the latest spec but so long as the AST datatypes haven't diverged then you should be able to integrate with the assembler.

If you fancy rewriting the lexer and parser to match the latest spec, go for it. Just overwrite the one in this repo with your version.
